In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.3.5


## 1) Creating Arrays: 

In [5]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [121]:
arr_list1 = np.array(list1)     #converting list to array using np.array
print(arr_list1)

[1 2 3]


In [7]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [8]:
list1 = [1,2,3]
list2 = [4,5,6]
arr_list1_2 = np.array([list1, list2])
print(arr_list1_2)

[[1 2 3]
 [4 5 6]]


In [10]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list1_3 = np.array([[list1, list2, list3]])
print(arr_list1_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [122]:
print(arr_list1_3.ndim)      #n.dim checks the dimention

3


## 2) Numpy Array Attributes:

In [202]:
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [123]:
print("shape" , arr1.shape)     #shape in 2D: (rows, columns)
print("size" , arr1.size)       # size checks number of elements
print("dType" , arr1.dtype)     #checks data type stored in the array
print("n_dim" , arr1.ndim)      #.ndim : dimention

shape (2, 3)
size 6
dType int64
n_dim 2


In [14]:
# HW- Create 2 array- 1D, 3D and find it's attributes.

In [127]:
arr_1d = np.array([1,2,3,4])

print("shape" , arr_1d.shape)
print("size" , arr_1d.size)
print("dType" , arr_1d.dtype)
print("n_dim" , arr_1d.ndim)

arr_3d = np.array([[[1,2,3,4],
                    [2,3,4,5],
                    [3,4,5,6]]])

print("shape" , arr_3d.shape)   
print("size" , arr_3d.size)
print("dType" , arr_3d.dtype)
print("n_dim" , arr_3d.ndim)

shape (4,)
size 4
dType int64
n_dim 1
shape (1, 3, 4)
size 12
dType int64
n_dim 3


In [128]:
arr_3d = np.array([[[1,2,3,4],
                    [2,3,4,5]],
                   
                   [[3,4,5,6],
                    [7,8,9,0]]])
print(arr_3d.shape)                #3D: (nums of overlaps, nums of rows, columns)

(2, 2, 4)


In [129]:
arr_3d = np.array([[[1,2,3,4],
                     [2,3,4,5]],
                   
                    [[3,4,5,6],
                     [7,8,9,0]],
                        
                    [[3,6,1,5],
                     [8,5,2,4]]])
print(arr_3d.shape)                 #3D: (nums of overlaps, nums of rows, columns)

(3, 2, 4)


# 2) Array Initialization Methods:

In [179]:
#zero array

zero_arr = np.zeros((2,3))     #(2,3) is (rows, columns) - 2D
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [131]:
#one array

one_arr = np.ones((1,3))      #(1,3) is (rows, columns) - 2D
print(one_arr)

[[1. 1. 1.]]


In [203]:
#full array

full_arr = np.full((3,2), 7)     # here (3,2) is (rows, columns) of the matrics, 7 is the value we want.
print(full_arr)

[[7 7]
 [7 7]
 [7 7]]


In [69]:
#identity matrix

id_arr = np.eye(4)       # 4 stands for 4 by 4 matrics, can be any number as our requirement.
print(id_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [70]:
#empty array - Prints any random values

print(np.empty(2))         # 2 - any random 2 values, it can be any number as our requirement.

[5.43230922e-312 7.29112202e-304]


In [205]:
#evenly spaced array

print(np.arange(1,5,1))        #starts from 1, prints values < 5 , adds 1 everytime, nums are changeable as requirement.

[1 2 3 4]


In [72]:
#specific number of equally spaced values between a range

print(np.linspace(1, 10, 4))      # dividing 1 - 10 in 4 parts equally (10-7 = 7-4 = 4-1)

[ 1.  4.  7. 10.]


In [133]:
#random values array- float

r_arr = np.random.rand(3,2)     #array of any random values of (3,2) order
print(r_arr)

[[0.64115173 0.44268393]
 [0.38155759 0.26691723]
 [0.3679265  0.59969585]]


In [132]:
#random values array- int

rint_arr = np.random.randint(1,10, (3,3))      #values in range 1 to 10, order (3,3)
print(rint_arr) 

[[8 6 1]
 [2 7 5]
 [4 5 3]]


# 3) Array Indexing & Slicing:

In [76]:
a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [78]:
print(a[0])     #accessing 1st element
print(a[2])     #accessing 3rd element
print(a[-2])    #accessing 2nd last element

1
5
7


In [206]:
#Slicing:
#array[start:stop:step]

In [85]:
print(a[0:3])  #first 3 elements

[1 3 5]


In [87]:
print(a[-3: ])   #last 3 elements

[5 7 9]


In [92]:
print(a[1:4])     #middle 3 elements

[3 5 7]


In [102]:
print(a[0:5:2])     #values from 0 to 5th indexing on every 2nd step

[1 5 9]


In [103]:
arr2 = np.array([[1,2,3],
                 [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [104]:
print(arr2[0])       #accessing 0th index of a 2D array

[1 2 3]


In [155]:
print(arr2[0][0])       #accessing 0th index's 0th index element of a 2D array 
print(arr2[0][1])       #accessing 0th index's 1st index element of a 2D array 
print(arr2[1][0])       #accessing 1st index's 0th index element of a 2D array 

1
2
4


In [142]:
print(arr2[1])        #indexing gives the array
print(arr2[1:])       #slicing gives array in dimension

[4 5 6]
[[4 5 6]]


In [139]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [146]:
print(arr2[:])

print(arr2[:, 0])         # 0 here gives 0th column, 1 gives 1st column, 2 gives 2nd column
print(arr2[:, 1])         # value after comma(,) indicates columns, values before comma indicates rows
print(arr2[:, 2])         # 3D: [layers/height, rows, columns]

[[1 2 3]
 [4 5 6]]
[1 4]
[2 5]
[3 6]


In [150]:
arr3 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [153]:
print(arr3[0])       #accessing 0th index of arr3
print(arr3[1])       #accessing 1st index of arr3
print(arr3[2])       #accessing 2nd index of arr3

[1 2 3]
[4 5 6]
[7 8 9]


In [156]:
print(arr3[0][2])       #accessing 0th index's 2nd index element of arr3
print(arr3[2][2])       #accessing 2nd index's 2nd index element of arr3

3
9


In [161]:
print(arr3[:, 2])    #2nd column's value (2- index)
print(arr3[:, 0])    #0th column's value (0- index)

[3 6 9]
[1 4 7]


In [167]:
print(arr3[::2])       #skips 1st index row because step mentioned is 2
print(arr3[::2, 0])     #0th index column from previous code's result. 

[[1 2 3]
 [7 8 9]]
[1 7]


In [176]:
#slicing on columns

print(arr3[::, 1:2])    #before "," - whole array , after "," - elements from 1st column, 2nd column excluded as indexing methods limits.

[[2]
 [5]
 [8]]


In [177]:
#slicing on rows & columns

print(arr3[1::, 1:2])   #exclude 0th index in rows(axis 0) as [1::] , excludes 0th index in column as [1:2]

[[5]
 [8]]


In [175]:
print(arr3[1::, 0:2])   #exclude 0th index in rows(axis 0) as [1::], exclude 2nd column as [0:2]- last mentioned index excluded.

[[4 5]
 [7 8]]


# 4) Array Reshaping & Flattening

In [180]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [184]:
reshaped = arr1.reshape((5,1))   #reshap method changes the order of the array as instructed
print(reshaped)                  #(5,1) - 5 rows & 1 column - Dimension = 2

[[1]
 [2]
 [3]
 [4]
 [5]]


In [188]:
arr2 = np.array([1,2,3,4,5,6])
print(arr2)
reshaped1 = arr2.reshape((2,3))      #(2,3) - 2 rows 3 columns
print(reshaped1)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [189]:
#Flattering reshapes multidimensional array to 1D array.
#It is opposite of reshaping

In [191]:
print(reshaped1.flatten())

[1 2 3 4 5 6]


In [193]:
list1 = [1,2,3,4]
list2 = [2,3,4,5]
list3 = [3,4,5,6]

array = np.array([list1, list2, list3])
print(array)

print(array.flatten())

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
[1 2 3 4 2 3 4 5 3 4 5 6]


# 5) Array Stacking & Splitting

In [196]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b)))     #vstack - vertical stacking - row wise
print(np.hstack((a,b)))     #hstack- horizontal stacking - column wise

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [199]:
c = np.array([[1,2,3], [3,4,5]])

print(c)

[[1 2 3]
 [3 4 5]]


In [216]:
split = np.hsplit(c,3)    #horizontally splitting into 3 parts as column1, 2 & 3 from array c
print(split)

for s in split:         #for better vizualisation & understanding
    print(s)

[array([[1],
       [3]]), array([[2],
       [4]]), array([[3],
       [5]])]
[[1]
 [3]]
[[2]
 [4]]
[[3]
 [5]]


In [217]:
vsplit = np.vsplit(c,2)     # vertically splitting c - array in 2 parts
print(vsplit)

vsplit_1 = np.vsplit(c,1)
print(vsplit_1)

[array([[1, 2, 3]]), array([[3, 4, 5]])]
[array([[1, 2, 3],
       [3, 4, 5]])]


# 6) Mathematical Operations on Array

In [220]:
a = np.array([10,20,40,-30])
print(a)

[ 10  20  40 -30]


In [265]:
print(a+10)               #adding 10 to every elements of array a
print(a-30)               #subtracting 30 from every elements of array a
print(a*2)                #multiplying every elements of array a by 10 
print(a/10)               #dividing every elements of array a by 10 

[11 12 13]
[-29 -28 -27]
[2 4 6]
[0.1 0.2 0.3]


In [223]:
b = np.array([1,4,9])
print(b)

[1 4 9]


In [229]:
print(np.square(b))        #square value
print(np.sqrt(b))          #square root value

[ 1 16 81]
[1. 2. 3.]


In [230]:
print(np.sin(b))
print(np.tan(b))
print(np.cos(b))

[ 0.84147098 -0.7568025   0.41211849]
[ 1.55740772  1.15782128 -0.45231566]
[ 0.54030231 -0.65364362 -0.91113026]


# 7) Mathematical Operations on Multiple Arrays

In [258]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a,b)

[1 2 3 4] [5 6 7 8]


In [235]:
print(np.add(a,b))             #adding a & b
print(np.subtract(a,b))        #subtracting b from a
print(np.multiply(a,b))        #multiplying a & b
print(np.divide(a,b))          #divide a by b

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


# 7.1) Dot Product

In [259]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a,b)

[1 2 3] [4 5 6]


In [260]:
#dot product - multiplies the elements column wise and then add the total 
#e.g; for a & b - 4*1 + 2*5 + 3*6 = 32

In [243]:
print(np.dot(a,b))

32


# 8) Transpose 

In [252]:
t = np.array([[1,2,3],
              [4,5,6]])
print(t)

[[1 2 3]
 [4 5 6]]


In [250]:
#transpose interchanges the rows and the columns

In [251]:
print(t.T)

[[1 4]
 [2 5]
 [3 6]]


# 9) Statistical Functions

In [255]:
a = np.array([[1,2,3],
              [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [256]:
print(np.sum(a))

21


In [257]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

3.5
3.5
1.707825127659933
1
6


# 10) Array Comparison

In [261]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [275]:
print( a == b)                     #comparing each element
print(np.array_equal(a,b))         #comparing the whole array at once using array_equal

[False False False False]
False


# 11) Broadcasting

In [267]:
a = np.array([1,2,3,4])
b = np.array([5])                 #doesn't show error in adding different shaped arrays
print(a+b)                        #adds b to all the elements of a

[6 7 8 9]


In [269]:
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[10,20,30]])
print(c+d)                                 #elements of d adds up to rows of c - [1+10 2+10 3+10] ...

[[11 22 33]
 [14 25 36]]


# 12) Handling nan & inf(infinite) values

In [271]:
data1 = np.array([1,2, np.nan, 4, np.inf])
print(data1)

[ 1.  2. nan  4. inf]


In [273]:
print(np.isnan(data1))                 #checking nan values using isnan

[False False  True False False]


In [276]:
print(np.nan_to_num(data1))            #replacing null values with numbers using nan_to_num

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


# 13) Save & Load Arrays

In [277]:
arr = np.array([1,0,0,8])
print(arr)
np.save("my_array.npy", arr)

[1 0 0 8]


In [278]:
loaded_arr = np.load("my_array.npy")
print(loaded_arr)

[1 0 0 8]
